### ISSUE TITLE
Exception in Extension Command Constructor

### ISSUE THREAD

**Issue by avodovnik** [AndreiMisiukevich/HotReload#127] opened 2020-01-14 09:28 UTC
Diagnosing some issues in VS for Mac, I've spotted a few stack traces with exceptions in your plugin. They seem to be coming from this part:

https://github.com/AndreiMisiukevich/HotReload/blob/c035c2df08407c74e4e987e7777711a0ba487f09/Extension/Xamarin.Forms.HotReload.Extension.MacVS/Commands/EnableExtensionCommand.cs#L12

(and the counterpart in `DisableExtensionCommand`)

Without looking deeper, I _suspect_ it's related to this being called too early in the overall process. You might want to reconsider the placement, or potentially checking `IdeApp.IsInitialized`.

**Comment by AndreiMisiukevich** [comment] 2020-01-14 15:53
how can I reproduce it?

**Comment by avodovnik** [comment] 2020-01-14 18:49
I haven't actually been able to reproduce it myself. I think it's got something to do with menus (particularly context menus) and somehow triggering them too early (i.e. before the caches are built, etc.). Although like I said, I haven't been able to repro it yet. I figured I should open an issue though, and at least give you a heads up that we're seeing this.

**Comment by AndreiMisiukevich** [comment] 2020-01-14 20:37
Thanks)

**Comment by AndreiMisiukevich** [comment] 2020-04-10 15:45
cannot reproduce
closing

**Closed by AndreiMisiukevich** 2020-04-10 15:45 UTC
Labels: cannot_reproduce, question
